### ISSUE TITLE
Bug -- HCM2 tooltip appears with a different font

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1246]
https://college-choice.18f.gov/school/?384412-University-of-the-Potomac-Washington-DC-Campus
Windows, Chrome

Not a problem on search results page, just on IHE page.

![image](https://cloud.githubusercontent.com/assets/13874735/9771471/713ace0c-5704-11e5-8a99-373c5c01cbc7.png)

**Comment by stevenbuccini** [comment]
FYI, following this link gives me a login prompt.

**Comment by onceuponatimeforever** [comment]
Not sure if this is a bug anymore, I can't see the difference between the fonts.

**Comment by claremccann** [comment]
This was resolved a while back.

**Comment by onceuponatimeforever** [comment]
Can you help close this issue?

**Comment by claremccann** [comment]
Actually, sorry, found the same bug again. It's fixed on the search results page, but not on the IHE pages. For instance, see: https://collegescorecard.ed.gov/school/?106306-Arkansas-Baptist-College and mouse over the (i) on the banner at the top of the page for ED monitoring.

**Comment by barkimedes** [comment]
Whoever wants to verify this bug once it's fixed, be sure to test it on Windows. Because when I check it on my Mac (Chrome), it looks more fixed, but on Windows (Chrome), it is clearly not fixed.
